server:
  port: 8888

spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/tttshop?createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        hbm2ddl.auto: update
    showSql: true